# Generated by Django 4.2.6 on 2023-12-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ecommerce_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
