# Generated by Django 4.2.4 on 2023-12-12 10:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecommerce_app', '0004_remove_orders_quantity_remove_orders_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_items',
            new_name='shipping',
        ),
    ]
